# Generated by Django 5.2.8 on 2025-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="lifestyledata", options={},),
        migrations.AlterField(
            model_name="lifestyledata", name="calories", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lifestyledata", name="sleep_hours", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="lifestyledata", name="steps", field=models.IntegerField(),
        ),
    ]
