# Generated by Django 5.2.8 on 2025-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_lifestyledata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lifestyledata", options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="lifestyledata",
            name="calories",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lifestyledata",
            name="sleep_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="lifestyledata",
            name="steps",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
